### ISSUE TITLE
Incorrect comment in generator.py function

### ISSUE THREAD

**Issue by mariakimheinert** [Allegheny-Computer-Science-280-F2017/cs280-F2017-lab2-starter#2]
The comment in the `generate()` function in `generator.py` contains the following comment
`""" Assumes that starting_ is a list. Removes any element from list_one that also occurs in list_two """`. 

This is not the expected behavior of the `generate()` function. It should read `""" Assumes that starting_ is a list. Produces, in addition to the input list (starting_list), a list of all the lists that can be obtained by swapping two adjacent items in the input list. """`

**Comment by mariakimheinert** [comment]
Created a pull request to address this issue: pull request https://github.com/Allegheny-Computer-Science-280-F2017/cs280-F2017-lab2-starter/pull/3

**Comment by gkapfham** [comment]
Hello @yeeunmariakim! Thanks for drawing attention to this issue. Yes, I acknowledge that there is a problem in the comments. However, this was one of the mistakes that I have purposefully "seeded" into the Python source code. I inserted this mistake on purpose so that students would have to think carefully about the inputs, outputs, and behavior of this function. I'm going to close this issue as I purposefully put this defect into the source code. With that said, keep an out out for problems like this in some of the upcoming laboratory assignments.
